<?php

/**
 * -----------------------------------------------------------------------------
 * Plugin Name: Shorten It
 * Description: Create short link for your post, your affiliates or your social content.
 * Version: 1.0.0
 * Requires PHP: 7.4
 * Requires CP: 2.0
 * Update URI: https://directory.classicpress.net/wp-json/wp/v2/plugins?byslug=xsx-shorten-it
 * Author: Simone Fioravanti
 * Author URI: https://software.gieffeedizioni.it
 * Plugin URI: https://software.gieffeedizioni.it
 * Text Domain: xsx-short-it
 * Domain Path: /languages
 * License: GPL2
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * -----------------------------------------------------------------------------
 * This is free software released under the terms of the General Public License,
 * version 2, or later. It is distributed WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. Full
 * text of the license is available at https://www.gnu.org/licenses/gpl-2.0.txt.
 * -----------------------------------------------------------------------------
 */

namespace XXSimoXX\ShortenIt;

class ShortenIt {

	private $options = false;
	const SLUG       = 'xsx-shorten-it';

	public function __construct() {
		add_action('template_redirect',          [$this, 'maybe_redirect']);
		add_action('admin_menu',                 [$this, 'create_settings_menu'], 100);
		register_uninstall_hook(__FILE__, [__CLASS__, 'uninstall']);
	}

	private function load_options() {
		if ($this->options !== false) {
			return;
		}
		$options = get_option('xsx_short_it', false);
		if ($options !== false) {
			$this->options = $options;
			return;
		}

		/* this creates a default for testing
		$this->options = [
			'ver'		  => '001',
			'paths'       => [
				'test' => [
					'dest' => 'https://educatorecinofilo.dog',
					'code' => '301',
					'hits' => 0,
				],
				'x' => [
					'dest' => 'https://gieffeedizioni.it',
					'code' => '302',
					'hits' => 10,
				],
			],
		];
		*/

		$this->options = [
			'ver'		  => '001',
			'paths'       => [],
		];
		$this->save_options();
	}

	private function save_options() {
		update_option('xsx_short_it', $this->options);
	}

	public function create_settings_menu() {
		$page = add_menu_page(
			esc_html__('Shorten It', 'xsx-short-it'),
			esc_html__('Shorten It', 'xsx-short-it'),
			'manage_options',
			self::SLUG,
			[$this, 'render_menu'],
			'dashicons-admin-links'
		);

		add_action('load-'.$page, [$this, 'delete_action']);
		add_action('load-'.$page, [$this, 'new_action']);
		add_action('load-'.$page, [$this, 'zero_action']);
	}

	public function render_menu () {

		echo '<div class="wrap">';

		$this->display_notices();

		echo '<div class="xsi xsi-general">';
		echo '<h1>'.esc_html__('Short It', 'xsx-short-it').'</h1>';
		echo '<p>'.esc_html__('Bla bla bla.', 'xsx-short-it').'</p>';
		echo '</div>';

		echo '<div class="xsi xsi-keys">';

		$this->load_options();
		$ListTable = new ShortItListTable();
		$ListTable->load_items($this->options['paths']);
		$ListTable->prepare_items();
		$ListTable->display();

		// echo '<p>'.esc_html__('You can add new magic links. Use the "Notes" field as a reminder. The key will be autogenerated.', 'xsx-under-construction').'<br>';
		// echo esc_html__('You can also delete magic links and people with that key will again be redirected to the Under Construction page.', 'xsx-under-construction').'</p>';

		echo '<form action="'.esc_url_raw(add_query_arg(['action' => 'new'], admin_url('admin.php?page='.self::SLUG))).'" method="POST">';
		wp_nonce_field('new', '_xsi');
		echo '<table class="form-table"><tr><td>';
		echo '<label for="new_path">'.esc_html__('Path: ', 'xsx-short-it').'</label></td>';
		echo '<td><input type="text" size="60" maxlength="60" name="new_path" id="new_path"></input></td></tr>';
		echo '<tr><td><label for="new_dest">'.esc_html__('Destination: ', 'xsx-short-it').'</label></td>';
		echo '<td><input type="text" size="60" maxlength="60" name="new_dest" id="new_dest"></input></td></tr>';
		echo '<tr><td><label for="new_code">'.esc_html__('Redirect type: ', 'xsx-short-it').'</label></td>';
		echo '<td><select name="new_code" id="new_code">';
		echo '	<option value="302">302 - Temporary</option>';
		echo '	<option value="307">307 - Temporary</option>';
		echo '	<option value="301">301 - Permanent</option>';
		echo '	<option value="308">308 - Permanent</option>';
		echo '</select></td></tr></table>';
		echo '<input type="submit" class="button button-primary" value="'.esc_html__('New short link', 'xsx-short-it').'"></input>';
		echo '</form>';
		echo '</div>';

		echo '</div>';

	}

	private function add_notice($message, $failure = false) {
		$other_notices = get_transient('xsx_short_it_notices');
		$notice = $other_notices === false ? '' : $other_notices;
		$failure_style = $failure ? 'notice-error' : 'notice-success';
		$notice .= '<div class="notice '.$failure_style.' is-dismissible go-away-soon">';
		$notice .= '    <p>'.wp_kses($message, ['br' => [], 'i' => [],]).'</p>';
		$notice .= '</div>';
		$notice .= '<script>jQuery(".go-away-soon").delay(3000).hide("slow", function() {});</script>';
		set_transient('xsx_short_it_notices', $notice, \HOUR_IN_SECONDS);
	}

	private function display_notices() {
		$notices = get_transient('xsx_short_it_notices');
		if ($notices === false) {
			return;
		}
		// This contains html formatted from 'add_notice' function that uses 'wp_kses'.
		echo $notices; //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		delete_transient('xsx_short_it_notices');
	}

	public function new_action() {

		if (!isset($_GET['action'])) {
			return;
		}
		if ($_GET['action'] !== 'new') {
			return;
		}
		if (!check_admin_referer('new', '_xsi')) {
			return;
		}
		if (!current_user_can('manage_options')) {
			return;
		}
		$missing = [];
		if (!isset($_REQUEST['new_path']) || $_REQUEST['new_path'] === '') {
			$missing[] = esc_html__('path', 'xsx-short-it');
		}
		if (!isset($_REQUEST['new_dest']) || $_REQUEST['new_dest'] === '') {
			$missing[] = esc_html__('destination', 'xsx-short-it');
		}
		if (!isset($_REQUEST['new_code']) || !in_array((int) $_REQUEST['new_code'], [301, 302, 307, 308])) {
			$missing[] = esc_html__('valid redirect type', 'xsx-short-it');
		}
		if ($missing !== []) {
			$error = sprintf(esc_html__('Missing %s.', 'xsx-short-it'), implode(', ', $missing));
			$this->add_notice($error, true);
			$sendback = remove_query_arg(['action', 'new_note', '_xuc'], wp_get_referer());
			wp_safe_redirect($sendback);
			exit;
		}

		$path = trim(sanitize_text_field(wp_unslash($_REQUEST['new_path'])), '/');
		$dest = esc_url_raw(wp_unslash($_REQUEST['new_dest']));
		$code = (int) sanitize_text_field(wp_unslash($_REQUEST['new_code']));

		$this->load_options();

		$this->options['paths'][$path] = [
				'dest'  => $dest,
				'code' => $code,
				'hits' => 0,
			];

		$this->save_options();
		$this->add_notice(esc_html__('New short URL generated.', 'xsx-short-it'), false);

		$sendback = remove_query_arg(['action', 'new_note', '_xuc'], wp_get_referer());
		wp_safe_redirect($sendback);
		exit;

	}

	public function delete_action() {

		if (!isset($_GET['action'])) {
			return;
		}
		if ($_GET['action'] !== 'delete') {
			return;
		}
		if (!check_admin_referer('delete', '_xsi')) {
			return;
		}
		if (!current_user_can('manage_options')) {
			return;
		}
		if (!isset($_REQUEST['path'])) {
			return;
		}

		$this->load_options();

		$path = sanitize_text_field(wp_unslash($_REQUEST['path']));
		unset($this->options['paths'][$path]);

		$this->save_options();
		$this->add_notice(esc_html__('Path deleted.', 'xsx-short-it').'<br><i>'.$path.'</i>', false);

		$sendback = remove_query_arg(['action', 'path', '_xsi'], wp_get_referer());
		wp_safe_redirect($sendback);
		exit;

	}

	public function zero_action() {

		if (!isset($_GET['action'])) {
			return;
		}
		if ($_GET['action'] !== 'zero') {
			return;
		}
		if (!check_admin_referer('zero', '_xsi')) {
			return;
		}
		if (!current_user_can('manage_options')) {
			return;
		}
		if (!isset($_REQUEST['path'])) {
			return;
		}

		$this->load_options();

		$path = sanitize_text_field(wp_unslash($_REQUEST['path']));
		$this->options['paths'][$path]['hits'] = 0;

		$this->save_options();
		$this->add_notice(esc_html__('Hits cleared.', 'xsx-short-it').'<br><i>'.$path.'</i>', false);

		$sendback = remove_query_arg(['action', 'path', '_xsi'], wp_get_referer());
		wp_safe_redirect($sendback);
		exit;

	}

	public function maybe_redirect() {
		if (defined('WP_CLI') && WP_CLI) {
			return;
		}

		$this->load_options();

		$path = sanitize_text_field(wp_unslash($_SERVER['REQUEST_URI'] ?? ''));
		$path = trim($path, '/');

		if (!array_key_exists($path, $this->options['paths'])) {
			return;
		}

		$this->options['paths'][$path]['hits']++;
		$this->save_options();

		//wp_redirect($this->options['paths'][$path]['dest'], (int) $this->options['paths'][$path]['code']); //phpcs:ignore WordPress.Security.SafeRedirect.wp_redirect_wp_redirect
		header('Location: '.$this->options['paths'][$path]['dest'], true, (int) $this->options['paths'][$path]['code']);
		exit();
	}

	public function styles() {
		wp_enqueue_style('xsx-under-construction-css', plugins_url('css/style.css', __FILE__), [], '0.0.2');
	}

	public static function uninstall() {
		delete_option('xsx_short_it');
	}

}

new ShortenIt;

if (!class_exists('WP_List_Table')) {
	require_once(ABSPATH.'wp-admin/includes/class-wp-list-table.php');
}

class ShortItListTable extends \WP_List_Table {

	// Contains the data to be rendered, as we want this to be passed from another class.
	private $paths = [];

	// Load list items, as we want this to be passed from another class.
	public function load_items($paths) {
		$this->paths = $paths;
	}

	// Output columns definition.
	public function get_columns() {
		return [
			'path' => esc_html__('Path', 'xsx-short-it'),
			'dest' => esc_html__('Destination', 'xsx-short-it'),
			'code' => esc_html__('Redirect code', 'xsx-short-it'),
			'hits' => esc_html__('Hits', 'xsx-short-it'),
		];
	}

	// Just output the column.
	public function column_default($item, $column_name) {
		return $item[$column_name];
	}

	// For "path" column add row actions.
	public function column_path($item) {
		$url = get_bloginfo('url').(str_starts_with($item['path'], '/') ? '' : '/').$item['path'];
		$actions = [
			'delete' => '<a href="'.wp_nonce_url(add_query_arg(['action' => 'delete', 'path' => $item['path']]), 'delete', '_xsi').'">'.esc_html__('Delete', 'xsx-short-it').'</a>',
			'reset' => '<a href="'.wp_nonce_url(add_query_arg(['action' => 'zero', 'path' => $item['path']]), 'zero', '_xsi').'">'.esc_html__('Reset count', 'xsx-short-it').'</a>',
			'copy'   => '<a href="#" onclick="navigator.clipboard.writeText(\''.$url.'\')">'.esc_html__('Copy URL to clipboard', 'xsx-short-it').'</a>',

		];
		$key = '<span class="row-title">'.$item['path'].'</span>';
		return sprintf('%1$s %2$s', $key, $this->row_actions($actions));
	}

	// For "destination" column link it.
	public function column_dest($item) {
		return '<a href="'.$item['dest'].'" target="_blank">'.$item['dest'].'</a>';
	}

	// Prepare our columns and insert data.
	public function prepare_items() {
		$columns  = $this->get_columns();
		$hidden   = [];
		$sortable = [];
		$this->_column_headers = [$columns, $hidden, $sortable];
		$data = [];
		foreach ($this->paths as $path => $options) {
			$data[] = [
				'path' => $path,
				'dest' => $options['dest'],
				'code' => $options['code'],
				'hits' => $options['hits'],
			];
		}
		$this->items = $data;
	}

}
