name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Create artifact
        run : |
          rm -f .gitignore
          git status
          stashName=`git stash create --all`;
          echo "Stash: "$stashName
          ls
          git archive -o ${{ github.event.repository.name }}-${{ github.ref_name }}.zip --prefix ${{ github.event.repository.name }}/ $stashName 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{ github.event.repository.name }}-${{ github.ref_name }}
            path: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
